### ISSUE TITLE
What should be changed in version 1.2? Should library maintenance continue?

### ISSUE THREAD

**Issue by kowalpy** [kowalpy/Robot-Framework-JMeter-Library#2]
Changes to be considered:

- [parsing changed log file format (JMeter >= 3.2)](https://github.com/kowalpy/Robot-Framework-JMeter-Library/issues/1)
- should library be compatible with file format generated by JMeter < 3.2 (new set of keywords ?)
- since JMeter 3.0 there is nice HTML dashboard available, does it even make sense to maintain this library? would anyone still use it having nice HTML report included in JMeter?

Library users please state your opinion as a comment to this issue

**Comment by banrieen** [comment]
Sorry, I did not follow the question in time .
First of all，The library even make sense to maintain, we can use RF maintain the jmeter scripts as testsuites or cases, and test cases are unified and maintained.

I think it is  necessary to parsing changed log file format (JMeter >= 3.2), because we can assert the result by keywords such as Analyse Jtl Convert ... , Log the steps or results in RF log.html and report.html

As JMeter < 3.2 no longer needed during testing, it is not import to be compatible.

**Comment by banrieen** [comment]
We usually like to execute the Jmter command  than GUI ，RF  provides a more convenient way to organize and manage jmeter test scripts。

**Comment by kowalpy** [comment]
I'll try to release 2.0 which will be able to parse either >3.2 JMeter or <
